---
language: javascript
tasks:
  build:
    command: vite
    args:
      - build
    inputs:
      - "**/*"
    type: node
  dev:
    command: vite
    inputs:
      - "**/*"
    options:
      runInCI: false
    type: node
